### PR TITLE
Factorial using Python

### PR DESCRIPTION
**Pull request by Nowshin1077**

### CODE REVIEW

**Comment by Nowshin1077** [comment]
Python program to find the factorial of a number.

**Comment by Nowshin1077** [comment]
A program to check if a number is prime or not.

**Comment by Nowshin1077** [comment]
A program to find the largest element from an array using C.

**Review by Rakeshgombi — APPROVED** [review]
@Nowshin1077 Congratulations on the successful submission of the PR. Remember that you have to make total of 4 pull request to become eligible for this cool swag. *Happy Hacktoberfest*😊

**Pull request merged**
